spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server

#eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
#eureka.instance.virtual-host-name
  client:
    register-with-eureka: false